import Providers from '@/components/Providers'
import './globals.css'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import store from '@/store/store'
import { StoreProviders } from '@/components/StoreProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
         <StoreProviders> 
        {children}
         </StoreProviders>
        </Providers>
        </body>
    </html>
  )
}
